### ISSUE TITLE
通过nn.Embedding.from_pretrained()加入了自己预训练的embedding向量，请问怎样在模型训练过程中，保持embeding不会被改变？

### ISSUE THREAD

**Issue by Qian-Hao** [GitHub-HongweiZhang/prediction-flow#26]
我在构建embedding的时候，通过nn.Embedding.from_pretrained()加入了自己预训练的embedding向量，请问怎样在模型训练过程中，保持embeding不会被改变？
![image](https://user-images.githubusercontent.com/39027475/81569181-865e5b00-93d1-11ea-800a-188511869263.png)

**Comment by GitHub-HongweiZhang** [comment]
模型的embeddings可以通过model.embeddings获得，然后用下面的方式把embeddings固定
requires_grad = False
具体看pytorch文档

https://github.com/GitHub-HongweiZhang/prediction-flow/blob/master/prediction_flow/pytorch/base.py#L23-L24

**Comment by Qian-Hao** [comment]
> 模型的embeddings可以通过model.embeddings获得，然后用下面的方式把embeddings固定
> requires_grad = False
> 具体看pytorch文档
> 
> https://github.com/GitHub-HongweiZhang/prediction-flow/blob/master/prediction_flow/pytorch/base.py#L23-L24

谢谢
