### ISSUE TITLE
请问您有完整复现过DIN论文中的movielen-20m实验吗？

### ISSUE THREAD

**Issue by Qian-Hao** [GitHub-HongweiZhang/prediction-flow#27]
我最近在做论文的实验，复现DIN的movielen实验，发现结果与论文相差很大。主要是不清楚数据集该如何预处理（打标签以及生成用户历史行为序列），请问您有完整做过这个实验吗？

**Comment by GitHub-HongweiZhang** [comment]
@Qian-Hao 

不好意思回晚了。我没有复现DIN的movielen实验，官方的repo没有预处理代码吗？
