### ISSUE TITLE
Incremental training

### ISSUE THREAD

**Issue by YahyaL** [GitHub-HongweiZhang/prediction-flow#29]
I am interested to use the DIEN model. What are the strategies to do incremental training to fit new user interactions and new items without having to retrain the whole model from scratch ?

I read the paper of the model and they only discuss how to reduce latency for model serving and not how to do incremental training.

**Comment by GitHub-HongweiZhang** [comment]
@YahyaL 

> incremental training.

I think the easiest way is to save and load the model many times.
when new data comes, load trained model, re-train using new data and save it.
