### ISSUE TITLE
pip install failed due to pandas issue

### ISSUE THREAD

**Issue by mkuymkuy** [GitHub-HongweiZhang/prediction-flow#31]
When I install with pip. An error occurred saying pandas built failed....
But my pandas is updated. Is there a way to use the package with "git clone"?

**Comment by GitHub-HongweiZhang** [comment]
> When I install with pip. An error occurred saying pandas built failed....

What is the error message? 

> But my pandas is updated. Is there a way to use the package with "git clone"?

Yes, you can just git clone the code, and import it.

**Comment by mkuymkuy** [comment]
> > When I install with pip. An error occurred saying pandas built failed....
> 
> What is the error message?
I cannot 100% remember the error message. But it ignored my pandas version with 1.6 and tried to install a version of 0.24. I guess it might be related to the pip install rules of the package. 
> 
> > But my pandas is updated. Is there a way to use the package with "git clone"?
> 
> Yes, you can just git clone the code, and import it.
Thanks. Will take a try.

**Comment by mkuymkuy** [comment]
> > When I install with pip. An error occurred saying pandas built failed....
> 
> What is the error message?
> 
> > But my pandas is updated. Is there a way to use the package with "git clone"?
> 
> Yes, you can just git clone the code, and import it.


Can you update the requirements.txt pandas ==0.24.2 to pandas >=0.24.2. It took me ages to build wheels for pandas 0.24.2 and failed miserably :(

**Comment by GitHub-HongweiZhang** [comment]
@mkuymkuy 

Sorry to be late. You can install 0.1.5 now.
https://github.com/GitHub-HongweiZhang/prediction-flow/pull/32
